# indexing, slicing and iteration  in numpy array

In [3]:

import numpy as np

In [13]:
arr12=np.arange(24)
arr12

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [14]:
arr13= np.arange(24).reshape(3,8)
arr13

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [15]:
arr12[3]

3

In [16]:
arr12[2:4]

array([2, 3])

In [17]:
arr12[-1]

23

In [20]:
arr13[2] # if we use indexing in 2d array we get rowof that array

array([16, 17, 18, 19, 20, 21, 22, 23])

In [22]:
arr13[:,2] # if we want to extract 2 nd column

array([ 2, 10, 18])

In [23]:
arr13[:,2:5]# for extracting multiple columns

array([[ 2,  3,  4],
       [10, 11, 12],
       [18, 19, 20]])

In [26]:
arr14=np.arange(24).reshape(6,4)
arr14

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [27]:
# we want to get 9,10,13,14 value from this array
arr14[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [28]:
arr14[4:6,2:4]

array([[18, 19],
       [22, 23]])

# iteration

In [29]:
arr13

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [30]:
arr14



array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [31]:
for i in arr14:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [32]:
for i in np.nditer(arr14):# eg if we want to put filter in every image then we do it in this logic
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
