# Reshaping numpy arrays

In [1]:
import numpy as np

In [7]:
arr4=np.arange(6,12).reshape(3,2)
arr4


array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [8]:
arr4.ndim

2

# Ravel functon is used to get higher dimensions array into one dimension


In [9]:
arr4.ravel() # array shape is now changed

array([ 6,  7,  8,  9, 10, 11])

# reshape 
this function only works when range is the factor of items eg 24 items then 6,4 or 4,6 or 8,3 or 3,8

# Transpose
convert the rows into column and vica versa

In [10]:
arr4.transpose()

array([[ 6,  8, 10],
       [ 7,  9, 11]])

assignment: if it is a 2d or 3d or multidimension array or vector in space, what would be the transpose ?

# stacking
It is a trick through which we can combine 2 arrays

In [11]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [15]:
arr3=np.array([0,1,2,3,4,5]).reshape(2,3)
arr3

array([[0, 1, 2],
       [3, 4, 5]])

In [17]:
arr4.reshape(2,3)


array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [18]:
arr5=np.arange(12,18).reshape(2,3)
arr5

array([[12, 13, 14],
       [15, 16, 17]])

In [20]:
np.hstack((arr3,arr5))#horizontally stacking

array([[ 0,  1,  2, 12, 13, 14],
       [ 3,  4,  5, 15, 16, 17]])

In [21]:
np.vstack((arr3,arr5))# verticel stacking

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [12, 13, 14],
       [15, 16, 17]])

real life senario example where this stacking can be useful
eg:  we can club the multiple column data having same header like name , marks of diffeent colleges 

# spliting the arrays

In [22]:
arr3

array([[0, 1, 2],
       [3, 4, 5]])

In [23]:
np.hsplit(arr3,3) # horizontally split the array into 3 parts 

[array([[0],
        [3]]),
 array([[1],
        [4]]),
 array([[2],
        [5]])]

In [24]:
np.vsplit(arr3,2) #vertically split the array into 2 parts

[array([[0, 1, 2]]), array([[3, 4, 5]])]

practically use of this eg: brachwise we have sorted the students then split the students acc to sections