In [1]:
# create numpy / n-d arrays
import numpy as np

In [2]:
arr1=np.array([1,2,3,4,5])#vector
arr1

array([1, 2, 3, 4, 5])

In [3]:
type(arr1)


numpy.ndarray

In [9]:
arr2=np.array([[23,45,67,89,98,32,4,2],[1,2,3,4,5,6,7,8]])
arr2

array([[23, 45, 67, 89, 98, 32,  4,  2],
       [ 1,  2,  3,  4,  5,  6,  7,  8]])

In [10]:
arr3=np.zeros((2,3)) #it created an ndarray throught the tuple share that is mentioneed 2,3 
arr3


array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
arr4=np.zeros((3,3))
arr4

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
type(arr4)

numpy.ndarray

In [15]:
arr5=np.ones((4,4))
arr5

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
type(arr5)

numpy.ndarray

In [17]:
arr6=np.identity(5) #diagonaly all the elements are ones in a 5x5 ,artics
arr6 #identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
arr7=np.arange(10) #arange gives a list in a given range 
arr7


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
arr7=np.arange(5,10)
arr7

array([5, 6, 7, 8, 9])

In [24]:
arr7=np.arange(5,10,1)
arr7

array([5, 6, 7, 8, 9])

In [41]:
arr8=np.linspace(10,20,10) #linspace need 3 inputs as lower range, upper range and the jump value range (equidistance points in a given ramge)  
arr8

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [28]:
arr9=arr8.copy()
arr9

array([10. , 12.5, 15. , 17.5, 20. ])

In [29]:
arr1.shape

(5,)

In [30]:
arr2.shape #2 rows and having 8 column

(2, 8)

In [34]:
arr10=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr10 #3d array 

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [35]:
arr10.shape #2 matrix  having 2 rows and 3 column

(2, 2, 3)

In [36]:
arr10.ndim

3

In [37]:
arr8.ndim

1

In [38]:
arr10.size # no of items

12

In [40]:
arr10.itemsize # 4 bits mnmory used by ecery item

4

In [42]:
arr8.itemsize #as the datatype is float it takes 8 bits of size in memory

8

In [44]:
arr8.dtype

dtype('float64')

In [45]:
arr10.dtype

dtype('int32')

In [46]:
#we can convert the datatype as per our requirement inside the nupy array
arr10.astype('float')#this function is used in cleaning data in real life(ML),to reduce the size of data eg-age should be in int  

array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]],

       [[ 7.,  8.,  9.],
        [10., 11., 12.]]])

In [50]:
# less memory
listA=range(100)
print(listA)

range(0, 100)


In [49]:
arr11=np.arange(100)
arr11

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [51]:
import sys #import module sys=system having function to get size of 

In [54]:
print(sys.getsizeof(87)*len(listA))#87 comes between 0 to 100 so it is the part of that list so it would be one item from the list, now it we multiple that one item with the size of theat list we get memory occupy by that list

2800


In [53]:
print(arr11.itemsize*arr11.size)

400


In [ ]:
# we can see the difference in above codes that array occupy less memory

In [55]:
#prove that numpy array is faster than python list
import time # import time module to prove this 


In [61]:
x=range(10000000)
y=range(10000000,20000000)

start_time=time.time()

c=[(x,y) for x,y in zip(x,y)] #zip is used to add and store in a new list

print(time.time()-start_time)

5.763486623764038


In [62]:
a=np.arange(10000000)
b=np.arange(10000000,20000000)

start_time=time.time()
c=a+b
print(time.time()-start_time)

1.140340805053711


In [ ]:
# it is proved now numpy array is faster

In [ ]:
#c syntax which is used in python lit is more complex than numpy array so it is proved that numpy array is more convenient
