# Some important NumPy functions

In [1]:
import numpy as np

In [3]:
# random module
np.random.random()

0.8982037854327635

In [8]:
np.random.seed(1)
np.random.random()# it will return sam erandom value again and again after runing the input

0.417022004702574

In [9]:
np.random.random()

0.7203244934421581

In [12]:
np.random.uniform(2,10) #  it will give any random float value between the given range i.e.,2,10

4.418660581054718

In [13]:
np.random.uniform(10,50)

15.870235632684523

In [15]:
np.random.uniform(2,10,10) # we will get 10 random value as the length given is 10 between the range 2,10

array([7.36374008, 5.33843842, 6.46951863, 3.12309551, 3.58481191,
       8.40595655, 9.74609261, 4.50739343, 7.53858093, 9.01111322])

In [16]:
np.random.uniform(2,10,10).reshape(2,5)# 2 such array with 5 length each

array([[9.15685331, 2.68035369, 2.31243827, 3.35864336, 9.02514003],
       [2.78677467, 5.368861  , 9.66311624, 6.26532228, 7.53501691]])

In [17]:
np.random.randint(1,18) # generating random integer

12

In [18]:
np.random.randint(1,10,15).reshape(3,5)

array([[5, 1, 4, 3, 1],
       [5, 3, 8, 8, 9],
       [7, 4, 8, 8, 5]])

In [19]:
a=np.random.randint(1,10,6)

In [20]:
a

array([6, 4, 7, 9, 1, 3])

In [21]:
np.max(a)


9

In [23]:
np.min(a)

1

In [24]:
np.argmax(a) # it will give the index of max in the array

3

In [25]:
np.argmin(a)

4

In [26]:
a[np.argmin(a)] # return the min value

1

In [27]:
a=np.random.randint(1,10,6)

In [28]:
a

array([8, 8, 8, 4, 1, 9])

In [29]:
a[a%2==1]=-1 # replace all the odd no with -1
a

array([ 8,  8,  8,  4, -1, -1])

In [32]:

a=np.random.randint(1,50,8)


In [33]:
a

array([14,  7, 22,  7,  3, 13, 28, 22])

In [34]:
a[a%2==1]=-1 
a

array([14, -1, 22, -1, -1, -1, 28, 22])

In [36]:
#where(conditon, True,False)
np.where(a%2==1,1,a)

array([14,  1, 22,  1,  1,  1, 28, 22])

In [37]:
out=np.where(a%2==1,-1,a)
out  #where command

array([14, -1, 22, -1, -1, -1, 28, 22])

In [38]:
a=np.random.randint(1,50,10)
a

array([12,  8, 14,  9, 12, 13, 44, 21, 31, 37])

In [39]:
a=np.sort(a)
a

array([ 8,  9, 12, 12, 13, 14, 21, 31, 37, 44])

In [40]:
#percentile function
np.percentile(a,25) #25%percentile

12.0

In [41]:
np.percentile(a,50)# we will get 50% of my array is less than that particular value

13.5

In [42]:
np.percentile(a,100)

44.0

In [44]:
np.percentile(a,99.8)

43.873999999999995