# Numpy array operations


In [1]:
import numpy as np

In [2]:
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([4,5,6,7,8,9])


In [4]:
arr1-arr2

array([-3, -3, -3, -3, -3, -3])

In [5]:
arr1*arr2 #vector multiplication

array([ 4, 10, 18, 28, 40, 54])

In [6]:
arr1*2 #scalor multiplication

array([ 2,  4,  6,  8, 10, 12])

In [8]:
arr1>3

array([False, False, False,  True,  True,  True])

In [9]:
arr3=np.arange(6).reshape(2,3)
arr4=np.arange(6,12).reshape(3,2)

In [11]:
arr3

array([[0, 1, 2],
       [3, 4, 5]])

In [12]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [13]:
arr3.dot(arr4)# dot multiplication of matrix

array([[ 28,  31],
       [100, 112]])

In [14]:
arr1.dot(arr3)# order doesn't match

ValueError: shapes (6,) and (2,3) not aligned: 6 (dim 0) != 2 (dim 0)

In [15]:
arr4.max()

11

In [16]:
arr4.min()

6

In [17]:
arr4.min(axis=0) #axis=0 column wise min

array([6, 7])

In [18]:
arr4.min(axis=1) #axis=1 row wise min

array([ 6,  8, 10])

In [19]:
arr4.sum()


51

In [20]:
arr4.sum(axis=1) # row wise sum

array([13, 17, 21])

In [21]:
arr4.sum(axis=0) # column wise sum

array([24, 27])

In [22]:
arr4.mean()


8.5

In [23]:
arr4.mean(axis=0) #column wise mean

array([8., 9.])

In [25]:
arr4.mean(axis=1) #row wise mean 

array([ 6.5,  8.5, 10.5])

In [26]:
arr4.std() # standard deviation

1.707825127659933

In [28]:
np.sin(arr4)

array([[-0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849],
       [-0.54402111, -0.99999021]])

In [29]:
np.median(arr4)

8.5

In [30]:
np.exp(arr4)


array([[  403.42879349,  1096.63315843],
       [ 2980.95798704,  8103.08392758],
       [22026.46579481, 59874.1417152 ]])

# np.exp(), np.sqrt(), np.sin() these are universal functions


#  uniary operations eg.,A.min(), A.sum(axis=0)